// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPortfolioServer.Context;

#nullable disable

namespace MyPortfolioServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240110102630_init9")]
    partial class init9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyPortfolioServer.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("Duration")
                        .HasColumnType("smallint");

                    b.Property<string>("PostURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İmageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.BlogTag", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BlogId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BlogTags");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35b99eb6-2438-41f6-aaba-9ffaacb5740e"),
                            Name = ".NET",
                            Status = "Backend",
                            URL = "NET_Core_Logo.svg.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("1ea5adab-6d18-4d0d-91a8-833958d65487"),
                            Name = "MSSQL",
                            Status = "Database",
                            URL = "mssql.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("b4bb205b-b169-48d2-b94f-cb51290f53fc"),
                            Name = "Angular",
                            Status = "Frontend",
                            URL = "angular.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("9f0a6096-63e9-4695-b398-d4ed00a7fa27"),
                            Name = "MongoDB",
                            Status = "Database",
                            URL = "mongo.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("661d88a9-45a3-4da2-b972-72b16d322b44"),
                            Name = "TypeScript",
                            Status = "Frontend",
                            URL = "typescript.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("2fda360d-ec30-473c-a9e6-679251da9986"),
                            Name = "JavaScript",
                            Status = "Frontend",
                            URL = "javascript.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("7664e5e3-286d-4c99-9680-a04b9a0767c0"),
                            Name = "HTML",
                            Status = "Frontend",
                            URL = "html.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        },
                        new
                        {
                            Id = new Guid("52e3d00a-122b-4f05-b022-a760b854c7f3"),
                            Name = "CSS",
                            Status = "Frontend",
                            URL = "css.png",
                            UserId = new Guid("9d06cf48-edca-4d1d-8f24-6539390b0d1b")
                        });
                });

            modelBuilder.Entity("MyPortfolioServer.Models.Thesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Thesises");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.UserDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.BlogTag", b =>
                {
                    b.HasOne("MyPortfolioServer.Models.Blog", "Blog")
                        .WithMany("BlogTags")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPortfolioServer.Models.Tag", "Tag")
                        .WithMany("BlogTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.UserDetail", b =>
                {
                    b.HasOne("MyPortfolioServer.Models.User", null)
                        .WithOne("UserDetail")
                        .HasForeignKey("MyPortfolioServer.Models.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPortfolioServer.Models.Blog", b =>
                {
                    b.Navigation("BlogTags");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.Tag", b =>
                {
                    b.Navigation("BlogTags");
                });

            modelBuilder.Entity("MyPortfolioServer.Models.User", b =>
                {
                    b.Navigation("UserDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
